// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthFlow struct {
	ID     int64
	UserID pgtype.Int8
	// 1=registration, 2=login, 3=recovery, 4=step_up_mfa
	FlowType int16
	// 1=pending_identifier, 2=pending_password, 3=pending_mfa, 4=pending_verification, 5=completed, 6=failed
	FlowState   int16
	IpAddress   pgtype.Text
	UserAgent   pgtype.Text
	Context     []byte
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type BackupCode struct {
	ID     int64
	UserID int64
	// Hash value using SHA-256 or bcrypt (preferred, since they are treated like passwords)
	Code      []byte
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Identity struct {
	ID     int64
	UserID int64
	// 1=google, 2=apple, 3=github, 4=facebook, 5=microsoft
	Provider        int16
	ProviderSubject string
	CreatedAt       pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type MfaFactor struct {
	ID     int64
	UserID int64
	// 1=totp, 2=sms, 3=email, 4=webauthn, 5=backup_code
	Type       int16
	Name       string
	CreatedAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Passkey struct {
	ID           int64
	UserID       int64
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Name         string
	Aaguid       pgtype.Text
	Transports   []string
	DeviceType   pgtype.Text
	BackedUp     bool
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

type PasswordCredential struct {
	UserID int64
	// Hash value using Argon2id (preferred) or bcrypt
	Password          string
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type RefreshToken struct {
	ID        int64
	SessionID int64
	// Hash value using SHA-256 of the actual refresh token
	Token      []byte
	IssuedAt   pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ReplacedBy pgtype.Int8
	CreatedIp  pgtype.Text
}

type SecurityEvent struct {
	ID     int64
	UserID pgtype.Int8
	// Examples: user.created, email.verified, login.failed, password.changed, mfa.enabled
	EventType string
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID     int64
	UserID int64
	// Hash value using SHA-256 of the actual session token sent to client
	Token         []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	IpAddress     pgtype.Text
	UserAgent     pgtype.Text
	MfaVerifiedAt pgtype.Timestamptz
}

type TotpFactor struct {
	FactorID int64
	// Encrypted value using AES-256-GCM or equivalent authenticated encryption
	Secret []byte
	// 1=SHA1, 2=SHA256, 3=SHA512
	Algorithm int16
	Digits    int16
	Period    int16
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID int64
	// 1=active, 2=inactive, 3=locked, 4=suspended, 5=deleted
	Status    int16
	Name      string
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type UserEmail struct {
	ID     int64
	UserID int64
	Email  string
	// User not allow two emails have is_primary=true
	IsPrimary  bool
	CreatedAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type UserPhoneNumber struct {
	ID     int64
	UserID int64
	// Phone number stored in E.164 international format (+1234567890).
	Phone      string
	CreatedAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type VerificationChallenge struct {
	ID         int64
	UserID     pgtype.Int8
	FlowID     pgtype.Int8
	Identifier string
	// 1=email_verification, 2=phone_verification, 3=password_reset, 4=mfa_verification, 5=magic_link
	Purpose int16
	// Hash value using SHA-256 of the OTP or Magic Link token sent
	Code        []byte
	Attempts    int16
	MaxAttempts int16
	IpAddress   pgtype.Text
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
