// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdentityByEmail = `-- name: GetIdentityByEmail :one
SELECT id, email, name, status
FROM identities
WHERE lower(email) = lower($1)
`

type GetIdentityByEmailRow struct {
	ID     int64
	Email  string
	Name   string
	Status int16
}

func (q *Queries) GetIdentityByEmail(ctx context.Context, email string) (GetIdentityByEmailRow, error) {
	row := q.db.QueryRow(ctx, getIdentityByEmail, email)
	var i GetIdentityByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, email, name, status
FROM identities
WHERE id = $1
`

type GetIdentityByIDRow struct {
	ID     int64
	Email  string
	Name   string
	Status int16
}

func (q *Queries) GetIdentityByID(ctx context.Context, id int64) (GetIdentityByIDRow, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i GetIdentityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getIdentityCredentialByIdentityID = `-- name: GetIdentityCredentialByIdentityID :one
SELECT id, identity_id, type, password_hash
FROM identity_credentials
WHERE identity_id = $1
  AND type = $2
`

type GetIdentityCredentialByIdentityIDParams struct {
	IdentityID int64
	Type       int16
}

type GetIdentityCredentialByIdentityIDRow struct {
	ID           int64
	IdentityID   int64
	Type         int16
	PasswordHash pgtype.Text
}

func (q *Queries) GetIdentityCredentialByIdentityID(ctx context.Context, arg GetIdentityCredentialByIdentityIDParams) (GetIdentityCredentialByIdentityIDRow, error) {
	row := q.db.QueryRow(ctx, getIdentityCredentialByIdentityID, arg.IdentityID, arg.Type)
	var i GetIdentityCredentialByIdentityIDRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Type,
		&i.PasswordHash,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, email, name, status, COUNT(*) OVER() AS total_count
FROM identities
WHERE ($1 IS NULL OR lower(email) = lower($1))
  AND ($2 IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY id
LIMIT $4 OFFSET $3
`

type ListIdentitiesParams struct {
	Email      interface{}
	Name       interface{}
	OffsetRows int32
	LimitRows  int32
}

type ListIdentitiesRow struct {
	ID         int64
	Email      string
	Name       string
	Status     int16
	TotalCount int64
}

func (q *Queries) ListIdentities(ctx context.Context, arg ListIdentitiesParams) ([]ListIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listIdentities,
		arg.Email,
		arg.Name,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentitiesRow
	for rows.Next() {
		var i ListIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
