// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT id, user_id, type, password_hash
FROM credentials
WHERE user_id = $1
  AND type = $2
`

type GetCredentialByUserIDParams struct {
	UserID int64
	Type   int16
}

type GetCredentialByUserIDRow struct {
	ID           int64
	UserID       int64
	Type         int16
	PasswordHash pgtype.Text
}

func (q *Queries) GetCredentialByUserID(ctx context.Context, arg GetCredentialByUserIDParams) (GetCredentialByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, arg.UserID, arg.Type)
	var i GetCredentialByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, status
FROM users
WHERE lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID     int64
	Email  string
	Name   string
	Status int16
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, status
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID     int64
	Email  string
	Name   string
	Status int16
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, status, COUNT(*) OVER() AS total_count
FROM users
WHERE ($1 IS NULL OR lower(email) = lower($1))
  AND ($2 IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY id
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Email      interface{}
	Name       interface{}
	OffsetRows int32
	LimitRows  int32
}

type ListUsersRow struct {
	ID         int64
	Email      string
	Name       string
	Status     int16
	TotalCount int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Email,
		arg.Name,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
