// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {"securitySchemes":{"BearerAuth":{"description":"Type \"Bearer\" followed by a space and JWT.","in":"header","name":"Authorization","type":"apiKey"}}},
    "info": {"contact":{"email":"support@oryon.com","name":"Contact Support","url":"https://oryon.com/contact"},"description":"{{escape .Description}}","license":{"name":"MIT","url":"https://mit-license.org/"},"termsOfService":"https://oryon.com/terms","title":"{{.Title}}","version":"{{.Version}}"},
    "externalDocs": {"description":"","url":""},
    "paths": {},
    "openapi": "3.1.0"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Oryon API",
	Description:      "Oryon provides authentication, authorization and profile management APIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
